# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='coordinate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
