# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0006_city_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night4', models.PositiveIntegerField(default=0)),
                ('morning5', models.PositiveIntegerField(default=0)),
                ('afternoon5', models.PositiveIntegerField(default=0)),
                ('night5', models.PositiveIntegerField(default=0)),
                ('morning6', models.PositiveIntegerField(default=0)),
                ('afternoon6', models.PositiveIntegerField(default=0)),
                ('night6', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.City')),
            ],
        ),
    ]
